<?php
/**
 * Created by PhpStorm.
 * User: 15899
 * Date: 2019/05/11
 * Time: 10:41
 */

namespace app\modules\goods;


class Module extends \yii\base\Module
{

    public $controllerNamespace = 'app\modules\goods\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}