<?php
/**
 ************************************
 *           Author: sunqiaoyu      *
 *         Date: 2019/03/05 17:55   *
 * **********************************
 **/

namespace app\controllers;

use yii\web\Controller;
use Yii;
use app\models\Menu;
use yii\web\Response;
use app\models\Accountcate;
use yii\helpers\ArrayHelper;

class BaseController extends Controller
{
    const ACCESS_KEY = "111";
    const SECRET_KEY = "111";
    const BUCKET_NAME = "image";
    public static $menus;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        // 在这里做用户登录检测
        if (Yii::$app->user->isGuest) {
            if (Yii::$app->request->isAjax) {
                echo json_encode([
                    'msg' => '需要登录',
                    'status' => 0,
                    'code' => 40001
                ]);
                exit;
            } else {
                header("Location:http://" . $_SERVER['HTTP_HOST'] . '/login/in');
                die();
            }
        }
        $tmp_menus = ArrayHelper::toArray(Menu::findAll(['status' => 1]));
        $accountcate = new Accountcate();
        $tmp_menus = $accountcate->toTree($tmp_menus,0);
        self::$menus = $accountcate->DASort($tmp_menus);
    }

    /**
     * response     返回JSON形式的数据
     * Date: 2019/2/19
     * Author: sunqiaoyu
     */
    public function response()
    {
        $response = Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
    }
}
